### PR TITLE
Update nodejs to 16.15.1 and npm to 8.12.1

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Comment by Page-** [comment]
@balena-ci retest

**Comment by Page-** [comment]
@balena-ci republish

**Comment by Page-** [comment]
@balena-ci republish

**Comment by nghiant2710** [comment]
@Page-, I will retest the PR when the base image is available

**Comment by nghiant2710** [comment]
@balena-ci retest

**Comment by nghiant2710** [comment]
@balena-ci retest

**Comment by Page-** [comment]
thanks @nghiant2710

**Comment by Page-** [comment]
@balena-ci republish

**Pull request merged**
