### PR TITLE
Update nodejs to 21.5.0

### PR DESCRIPTION
**Pull request by Page-**
Change-type: major

### CODE REVIEW

**Comment by joshbwlng** [comment]
@Page- Node 21.5.0 is out now if you want to go ahead and bump to that? https://github.com/nodejs/node/releases

**Comment by thgreasi** [comment]
I'm fine with it but I'm curious how you changed your mind about non-LTS releases :thinking: 
Was it the ESM improvements? Was it the WebStreams & WebSockets?

**Review by thgreasi — APPROVED** [review]

**Comment by thgreasi** [comment]
I mean, the nodejs website even says:
> Production applications should only use Active LTS or Maintenance LTS releases.

See:

**Comment by Page-** [comment]
@thgreasi you were in the call where we discussed this and decided it makes sense for us

**Pull request merged**
